### ISSUE TITLE
Stream Personalization

### ISSUE THREAD

**Issue by mrfizzl3** [mrfizzl3/Red-DiscordBot#11]
Please be sure to read through other issues as well to make sure what you are suggesting/reporting has not already
been suggested/reported

### Type:

- [ ] Suggestion
- [x] Bug

#8
### Brief description of the problem
```python
[13/12/2017 22:43] ERROR owner load 69: ('invalid syntax', ('C:\\Users\\Administrator\\Desktop\\Kermit\\Red-DiscordBot\\cogs\\streams.py', 604, 47, '                            if stream["NAME"] = piano_tv\n'))
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\Kermit\Red-DiscordBot\cogs\owner.py", line 946, in _load_cog
    mod_obj = importlib.import_module(cogname)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "C:\Users\Administrator\Desktop\Kermit\Red-DiscordBot\cogs\streams.py", line 604
    if stream["NAME"] = piano_tv
                      ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\Kermit\Red-DiscordBot\cogs\owner.py", line 65, in load
    self._load_cog(module)
  File "C:\Users\Administrator\Desktop\Kermit\Red-DiscordBot\cogs\owner.py", line 950, in _load_cog
    raise CogLoadError(*e.args)
cogs.owner.CogLoadError: ('invalid syntax', ('C:\\Users\\Administrator\\Desktop\\Kermit\\Red-DiscordBot\\cogs\\streams.py', 604, 47, '                            if stream["NAME"] = piano_tv\n'))
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\Kermit\Red-DiscordBot\cogs\owner.py", line 946, in _load_cog
    mod_obj = importlib.import_module(cogname)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "C:\Users\Administrator\Desktop\Kermit\Red-DiscordBot\cogs\streams.py", line 604
    if stream["NAME"] = piano_tv
                      ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\Kermit\Red-DiscordBot\cogs\owner.py", line 65, in load
    self._load_cog(module)
  File "C:\Users\Administrator\Desktop\Kermit\Red-DiscordBot\cogs\owner.py", line 950, in _load_cog
    raise CogLoadError(*e.args)
cogs.owner.CogLoadError: ('invalid syntax', ('C:\\Users\\Administrator\\Desktop\\Kermit\\Red-DiscordBot\\cogs\\streams.py', 604, 47, '                            if stream["NAME"] = piano_tv\n'))
```
### Expected behavior
If piano_tv were to go live (or the online status was checked) it would return 

> @here @Piano is live! (followed by the rich embed)

### Actual behavior
Syntax error above

**Comment by mrfizzl3** [comment]
It's too late and I'm too tired/lazy to fix this. #10 will do for now.
